version: '3.8'

services:
  app:
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - CONTRACT=0xc81feadcbcd93dd4bb0a0760f9a9fc8348ea8dee
    stdin_open: true
    tty: true
